export const TOGGLE_FAVORITE = "CONTENT.TOGGLE_FAVORITE";
export const REMOVE_FAVORITE = "CONTENT.REMOVE_FAVORITE";
export const ADD_FAVORITE = "CONTENT.ADD_FAVORITE";

export const MOVIES_REQ = "CONTENT.MOVIES_REQ";
export const MOVIES_SUCESS = "CONTENT.MOVIES_SUCESS";
export const MOVIES_FAILURE = "CONTENT.MOVIES_FAILURE";

export const SINGLE_MOVIE_REQ = "CONTENT.SINGLE_MOVIE_REQ";
export const SINGLE_MOVIE_SUCESS = "CONTENT.SINGLE_MOVIE_SUCESS";
export const SINGLE_MOVIE_FAILURE = "CONTENT.SINGLE_MOVIE_FAILURE";
